name: Matrix demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12,14,16]
                operating-sys: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 18
                      operating-sys: ubuntu-latest
                exclude: 
                    - node-version: 12
                      operating-sys: windows-latest
        runs-on: ${{ matrix.operating-sys }}
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: installing dependencies
              run: npm ci
            - name: build project
              run: npm run build